// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cFQCkFbaGIu31oGbN1r-4cAOrMjifQA',
    appId: '1:403107765295:web:341a648d016cf6923bbada',
    messagingSenderId: '403107765295',
    projectId: 'zen-b1-ilkom',
    authDomain: 'zen-b1-ilkom.firebaseapp.com',
    storageBucket: 'zen-b1-ilkom.appspot.com',
    measurementId: 'G-Y0XSM94BPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw-5ABJWFdIlnuoMrF8fTJnEhAjlA8ybc',
    appId: '1:403107765295:android:abadfad15b90a71e3bbada',
    messagingSenderId: '403107765295',
    projectId: 'zen-b1-ilkom',
    storageBucket: 'zen-b1-ilkom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAce8VB2y5xFVaVJ9-gz1drI62QMmW8WRg',
    appId: '1:403107765295:ios:9b66055db11918863bbada',
    messagingSenderId: '403107765295',
    projectId: 'zen-b1-ilkom',
    storageBucket: 'zen-b1-ilkom.appspot.com',
    iosBundleId: 'com.example.semester3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAce8VB2y5xFVaVJ9-gz1drI62QMmW8WRg',
    appId: '1:403107765295:ios:9b66055db11918863bbada',
    messagingSenderId: '403107765295',
    projectId: 'zen-b1-ilkom',
    storageBucket: 'zen-b1-ilkom.appspot.com',
    iosBundleId: 'com.example.semester3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cFQCkFbaGIu31oGbN1r-4cAOrMjifQA',
    appId: '1:403107765295:web:f0339e22fcdddabc3bbada',
    messagingSenderId: '403107765295',
    projectId: 'zen-b1-ilkom',
    authDomain: 'zen-b1-ilkom.firebaseapp.com',
    storageBucket: 'zen-b1-ilkom.appspot.com',
    measurementId: 'G-GVTSY8LF38',
  );
}
